name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # 使用3.2版本
          bundler-cache: true  # 自动缓存bundler
      
      - name: Debug information
        run: |
          echo "Ruby version: $(ruby --version)"
          echo "Bundler version: $(bundle --version)"
          echo "Gemfile content:"
          cat Gemfile
          echo "---"
      
      - name: Install dependencies
        run: bundle install
      
      - name: Verify Jekyll installation
        run: |
          bundle show jekyll
          bundle exec jekyll --version
      
      - name: Build with Jekyll
        run: bundle exec jekyll build -d _site --trace
      
      - name: List built files
        run: ls -la _site/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
